Document: a2site
Title: Debian a2site Manual
Author: <insert document author here>
Abstract: This manual describes what a2site is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/a2site/a2site.sgml.gz

Format: postscript
Files: /usr/share/doc/a2site/a2site.ps.gz

Format: text
Files: /usr/share/doc/a2site/a2site.text.gz

Format: HTML
Index: /usr/share/doc/a2site/html/index.html
Files: /usr/share/doc/a2site/html/*.html
